name: Create Release
on:
  workflow_dispatch:

jobs:
  bosh_release_create_candidate:
    runs-on: ubuntu-latest
    container:
      image: 'mcr.microsoft.com/devcontainers/base:ubuntu'

    steps:
    - name: Checkout cli bosh release repo
      uses: actions/checkout@v4

    - name: Create bosh release candidate
      env:
        TRACE: 1
      run: env | sort && git status