name: Create Release
on:
  workflow_dispatch:

jobs:
  bosh_release_create_candidate:
    runs-on: ubuntu-latest
    container:
      image: 'ghcr.io/chinigorg/bosh-package-cf-cli-release-ci:187042013-release-workflow-latest'

    steps:
    - name: Checkout cli bosh release repo
      uses: actions/checkout@v4

    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
      with:
        wait-timeout-minutes: 15

    - name: Create bosh release candidate
      env:
        TRACE: 1
        
      run: ./ci/scripts/create-bosh-release-candidate.sh
