name: Lint shell scripts
on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout cli bosh release repo
      uses: actions/checkout@v4

    - name: Install shellcheck
      run: apt update && apt install -y shellcheck

    - name: lint
      run: find ./ci -type f -name '*.sh' | xargs -t shellcheck